/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_orctom_speex4j_SpeexDecoder
#define _Included_com_orctom_speex4j_SpeexDecoder
#ifdef __cplusplus
extern "C" {
#endif
/* DO NOT EDIT THIS FILE - it is machine generated */
JNIEXPORT jbyteArray JNICALL Java_com_orctom_speex4j_SpeexDecoder_decode
  (JNIEnv *, jclass, jint, jbyteArray, jint length, jbyteArray, jint index);

JNIEXPORT jint JNICALL Java_com_orctom_speex4j_SpeexDecoder_allocate
  (JNIEnv *, jclass, jint);

JNIEXPORT void JNICALL Java_com_orctom_speex4j_SpeexDecoder_deallocate
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif