/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_orctom_speex4j_SpeexCodec */

#ifndef _Included_com_orctom_speex4j_SpeexCodec
#define _Included_com_orctom_speex4j_SpeexCodec
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_orctom_speex4j_SpeexCodec
 * Method:    encode
 * Signature: (III[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_orctom_speex4j_SpeexCodec_encode
        (JNIEnv *, jobject, jint, jint, jint, jshortArray, jbyteArray);

/*
 * Class:     com_orctom_speex4j_SpeexCodec
 * Method:    decode
 * Signature: (II[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_orctom_speex4j_SpeexCodec_decode
  (JNIEnv *, jobject, jint, jbyteArray, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
