/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_orctom_speex4j_SpeexEncoder */

#ifndef _Included_com_orctom_speex4j_SpeexEncoder
#define _Included_com_orctom_speex4j_SpeexEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_orctom_speex4j_SpeexEncoder
 * Method:    open
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_orctom_speex4j_SpeexEncoder_open
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_orctom_speex4j_SpeexEncoder
 * Method:    encode
 * Signature: ([S[B)I
 */
JNIEXPORT jint JNICALL Java_com_orctom_speex4j_SpeexEncoder_encode
  (JNIEnv *, jobject, jshortArray, jbyteArray);

/*
 * Class:     com_orctom_speex4j_SpeexEncoder
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_orctom_speex4j_SpeexEncoder_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
