/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_orctom_speex4j_SpeexDecoder */

#ifndef _Included_com_orctom_speex4j_SpeexDecoder
#define _Included_com_orctom_speex4j_SpeexDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_orctom_speex4j_SpeexDecoder
 * Method:    open
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_orctom_speex4j_SpeexDecoder_open
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_orctom_speex4j_SpeexDecoder
 * Method:    decode
 * Signature: ([B[S)I
 */
JNIEXPORT jint JNICALL Java_com_orctom_speex4j_SpeexDecoder_decode
  (JNIEnv *, jobject, jbyteArray, jshortArray);

/*
 * Class:     com_orctom_speex4j_SpeexDecoder
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_orctom_speex4j_SpeexDecoder_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
